name = "ssdp-invoice-generator"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespace for invoice storage
[[kv_namespaces]]
binding = "SSDP_KV"
id = "ssdp_kv_namespace"

# Environment variables
[vars]
ZATCA_API_URL = "https://api.zatca.gov.sa"

# Secrets (set via: wrangler secret put ZATCA_API_KEY)
# ZATCA_API_KEY = ""
