name = "ssdp-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "SSDP_DB"
database_name = "brainsait"
database_id = "68230ad3-2a43-41dc-9716-f5aa6fed137c"

# KV Namespace
[[kv_namespaces]]
binding = "SSDP_KV"
id = "5a0569ad74774d3998edd1df1f59e950"

# Environment Variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
