name = "ssdp-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ssdp-api"
route = "api.ssdp.brainsait.com/*"

[env.staging]
name = "ssdp-api-staging"
route = "api-staging.ssdp.brainsait.com/*"

# D1 Database
[[d1_databases]]
binding = "SSDP_DB"
database_name = "ssdp-database"
database_id = "your-d1-database-id"

# KV Namespace
[[kv_namespaces]]
binding = "SSDP_KV"
id = "your-kv-namespace-id"
preview_id = "your-kv-preview-id"

# R2 Bucket
[[r2_buckets]]
binding = "SSDP_R2"
bucket_name = "ssdp-assets"

# Environment Variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"

# Secrets (set via wrangler secret put)
# WATHQ_API_KEY
# ZATCA_API_KEY
# JWT_SECRET

# Analytics
[analytics_engine_datasets]
binding = "SSDP_ANALYTICS"

# Durable Objects
[[durable_objects.bindings]]
name = "SSDP_REALTIME"
class_name = "RealtimeHandler"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Triggers
[[triggers.crons]]
cron = "0 */6 * * *"  # Every 6 hours
