name: Validate Copilot Instructions
permissions:
  contents: read

on:
  pull_request:
    paths:
      - '.github/copilot-instructions.md'
      - 'AGENTS.md'
      - '.instructions/**'
  push:
    branches: [main, master, develop]
    paths:
      - '.github/copilot-instructions.md'
      - 'AGENTS.md'
      - '.instructions/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Copilot Instructions
        run: |
          chmod +x scripts/validate-copilot.sh
          ./scripts/validate-copilot.sh

      - name: Check BrainSAIT OID usage
        run: |
          echo "Checking for BrainSAIT OID namespace (1.3.6.1.4.1.61026)..."

          # Check main copilot-instructions.md
          if grep -q "1.3.6.1.4.1.61026" .github/copilot-instructions.md; then
            echo "✅ BrainSAIT OID found in copilot-instructions.md"
          else
            echo "❌ BrainSAIT OID NOT found in copilot-instructions.md"
            exit 1
          fi

          # Check FHIR instructions
          if grep -q "1.3.6.1.4.1.61026" .instructions/fhir-instructions.md; then
            echo "✅ BrainSAIT OID found in fhir-instructions.md"
          else
            echo "❌ BrainSAIT OID NOT found in fhir-instructions.md"
            exit 1
          fi

          # Check AGENTS.md
          if grep -q "1.3.6.1.4.1.61026" AGENTS.md; then
            echo "✅ BrainSAIT OID found in AGENTS.md"
          else
            echo "❌ BrainSAIT OID NOT found in AGENTS.md"
            exit 1
          fi

          echo "✅ All files contain correct BrainSAIT OID namespace"

      - name: Verify frontmatter in instruction files
        run: |
          echo "Checking frontmatter in instruction files..."

          for file in .instructions/*.md; do
            if [ -f "$file" ]; then
              if grep -q "^---$" "$file" && grep -q "^applyTo:" "$file"; then
                echo "✅ Valid frontmatter in: $file"
              else
                echo "❌ Invalid frontmatter in: $file"
                exit 1
              fi
            fi
          done

      - name: Check file sizes
        run: |
          echo "Checking instruction file sizes..."

          for file in .github/copilot-instructions.md AGENTS.md .instructions/*.md; do
            if [ -f "$file" ]; then
              size=$(wc -c < "$file")
              kb=$((size / 1024))
              echo "📄 $file: ${kb}KB"

              if [ $size -gt 102400 ]; then
                echo "⚠️  Warning: $file is larger than 100KB"
              fi
            fi
          done

      - name: Validation summary
        if: success()
        run: |
          echo "✅ All validation checks passed!"
          echo ""
          echo "BrainSAIT Copilot Instructions validated:"
          echo "  - Main instructions: .github/copilot-instructions.md"
          echo "  - AI agents config: AGENTS.md"
          echo "  - FHIR instructions: .instructions/fhir-instructions.md"
          echo "  - UI instructions: .instructions/ui-instructions.md"
          echo "  - API instructions: .instructions/api-instructions.md"
          echo ""
          echo "OID Namespace: 1.3.6.1.4.1.61026"
          echo "  ├── Sudan: .1"
          echo "  └── Saudi Arabia: .2"
